name: Update gh-pages

on:
  push:
    branches:
      - master

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        
      - name: Copy files to gh-pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout master
          git checkout gh-pages
          cp -r src/dist/* .
          git add .
          git commit -m "Update gh-pages from master" || echo "No changes to commit"
          git push origin gh-pages
